### ISSUE TITLE
Fails on unknown field

### ISSUE THREAD

**Issue by djui** [mvdan/interfacer#11]
Running the tool on the follow code fails with the error:

```
$ interfacer ./...
p/a/t/h/main.go:185:3: unknown field Pdeathsig in struct literal
```

```go
cmd := exec.Command("foo")
cmd.SysProcAttr = &syscall.SysProcAttr{
    Pdeathsig: syscall.SIGTERM,
}
```

**Comment by mvdan** [comment]
Care to elaborate?

**Comment by djui** [comment]
Sorry, the issue got sent accidentally before I could compose.

**Comment by mvdan** [comment]
I just put together a simple test case and it works for me.

If you look at https://golang.org/pkg/syscall/#SysProcAttr, you'll see that this is a linux-only field. Maybe you're trying to run this on a non-linux platform?

**Comment by mvdan** [comment]
To elaborate, `interfacer` should fail just like `go build`, `gotype` and the rest of tools. Either that, or none of them should have this error.

**Comment by djui** [comment]
That's correct. I usually ran the code in a Docker container, but to test Interfacer I ran it on my OSX and therefore saw the error. I guess we can close that issue.
