### ISSUE TITLE
Don't warn about struct types passed by value

### ISSUE THREAD

**Issue by mvdan** [mvdan/interfacer#19]
See the discussion in #17.

Basically, it seems that warning aobut parameter types that are passed by value and not by reference is not a good idea. The cause is that passing by reference means that the data is copied to the heap, which might be a noticeable overhead if it's a hot path or if the struct is large and not already in the heap.

Some questions come to mind:

* Should this apply to all types, not just structs?

```go
type foo string
func (f foo) Close() error {}

func bar(f foo) { // Should we warn about io.Closer?
    f.Close()
}
```

* If it only applies to structs, should we keep the struct size in mind?

* Should this apply only to unexported functions? I would think they are more likely to be hot paths, where such copying overhead could be an issue. Public APIs shouldn't be tuned for speed, I would think.

**Comment by mvdan** [comment]
@tamird any ideas?

**Comment by tamird** [comment]
> If it only applies to structs, should we keep the struct size in mind?

Struct size doesn't matter - copying is cheap, it's the heap allocation that's expensive.

> Should this apply only to unexported functions? I would think they are more likely to be hot paths, where such copying overhead could be an issue. Public APIs shouldn't be tuned for speed, I would think.

Yeah, that could be a reasonable compromise.
