### ISSUE TITLE
Cooler example

### ISSUE THREAD

**Issue by ahmetalpbalkan** [mvdan/interfacer#21]
If you change the example as:

```diff
func ProcessInput(f *os.File) error {
+       defer f.Close()
        b, err := ioutil.ReadAll(f)
        if err != nil {
                return err
        }
        return processBytes(b)
}
```

it suggests `io.ReadCloser`, which IMO is really cool... Thanks for this project!

**Comment by mvdan** [comment]
Thanks for the suggestion!

Indeed this is a cooler example. At the same time, I'm thinking that it doesn't make a lot of sense as code in real life. Usually the function that opens the file does the `defer f.Close()`. I was going for the shorter code snippet possible that was both realistic and still a neat example.

What do you think?

**Comment by mvdan** [comment]
I'm happy with the current example, so for now I'm closing this.
