### ISSUE TITLE
Poorly behaved on *_test files

### ISSUE THREAD

**Issue by siddharthist** [mvdan/interfacer#24]
I have been running interfacer with [neomake](https://github.com/benekastah/neomake) whenever I save a golang file. This has been working fine, until I attempted to edit a _test.go file, where I recieved the following error:
```
$ interfacer smlr/http_test.go 
smlr/http_test.go:22:12: undeclared name: HTTPWaiter
```
(where `HTTPWaiter` is declared in `smlr/http.go). Many other tools handle this discrepancy well, I wonder if interfacer could. 

Unfortunately, I can't tell you what version of interfacer this is:
```
$ interfacer --version
flag provided but not defined: -version
Usage of interfacer:
  -v	print the names of packages as they are checked
```

Here is my neomake configuration, if that helps:
```viml
let g:neomake_go_interfacer_maker = {
    \ 'errorformat': '%f:%l:%c: %m'
    \ }
let g:neomake_go_enabled_makers = ['go', 'golint', 'govet', 'interfacer']
```

**Comment by mvdan** [comment]
Interesting. I'll look into this, thanks!

**Comment by mvdan** [comment]
Are you sure linters should be used this way? I've checked a few other linters, including @dominikh's unused, and most of them error. Or at least those using `go/types` like this one.

**Comment by dominikh** [comment]
Tools such as unused or interfacer care about the whole package (they have to, in order to type-check it). Passing individual files to them will not work. Tools that do support it either only look at the AST (gofmt) or are fine with partial type information (go vet).

**Comment by mvdan** [comment]
This is what I was thinking. Something we could do, though, is replace any number of source files with their package (in this case `.`) then only produce warnings for the wanted files. We're still parsing the whole package, but at least we'll be skipping the unwanted files from the fileset.

**Comment by dominikh** [comment]
You can do that (`buildutil.ContainingPackage`), but be aware of these two use cases: having a single-file "package" that's not in a GOPATH at all, and specifying multiple files to explicitly omit files from a package. The former is much more common and easy to handle. I don't know how common the second use case is. It can probably be disregarded (though that'll mean that behaviour differs from, say, `go build`)

**Comment by mvdan** [comment]
We already handle the first one, don't we?

I'm inclined to close this as wontfix, or rather, "can't fix in a way that doesn't overcomplicate things"`

**Comment by dominikh** [comment]
If you switched to doing "replace any number of source files with their package" like you suggested, then you'd need to handle the first case explicitly, as that file won't have an import path.

**Comment by mvdan** [comment]
I'm going to go with the lazy approach and not consider fixing this at the moment.
