### ISSUE TITLE
Provide --version flag

### ISSUE THREAD

**Issue by siddharthist** [mvdan/interfacer#25]
It's good for debugging/reporting errors!
```
$ interfacer --version
flag provided but not defined: -version
Usage of interfacer:
  -v	print the names of packages as they are checked
```

**Comment by mvdan** [comment]
This program has no versions :) If you installed via `go get`, you can tell the version by just doing:

```sh
cd $GOPATH/src/github.com/mvdan/interfacer
git rev-parse HEAD
```

**Comment by shurcooL** [comment]
If you happen to have [`binstale`](https://godoc.org/github.com/shurcooL/binstale), you could ensure your installed binary version is not out of date compared to the source code.

If not, you can just `go install -v github.com/mvdan/interfacer` and make sure it doesn't print anything (if it does, that means the binary _was_ stale, but is now up to date).

**Comment by mvdan** [comment]
@shurcooL surely you want `-u` in there too?

**Comment by shurcooL** [comment]
I was referring to the locally available source and binary. One should indeed use `go get -u github.com/mvdan/interfacer` to update (over the network) to the latest remote version and install it.

**Comment by mvdan** [comment]
Ah, OK. Just making sure :)

I'm closing this as I don't think every single Go tool and linter should reinvent the wheel when it comes to versioning. Especially when versions aren't really needed anyway.

**Comment by henvic** [comment]
Hey, you should at least consider adding https://github.com/mvdan/interfacer to the --help.

**Comment by mvdan** [comment]
```
$ golint -h
Usage of golint:
        golint [flags] # runs on package in current directory
        golint [flags] package
        golint [flags] directory
        golint [flags] files... # must be a single package
Flags:
  -min_confidence float
        minimum confidence of a problem to print it (default 0.8)
[mvdan@carbon:pts/7] [11:39] [/home/mvdan] [2]
$ interfacer -h
Usage of interfacer:
  -v    print the names of packages as they are checked
```
