### ISSUE TITLE
It is better for interfacer not to analyze vendor folder

### ISSUE THREAD

**Issue by bigwhite** [mvdan/interfacer#27]
interfacer is a good tool for gophers. I have tried it and got many help. I have a small issue that is currently the interfacer tries to analyze the vendor folder in the golang repo. In my opinion, It is better for interfacer not to analyze vendor folder.

```
$interfacer ./...
/Users/tony/Test/GoToolsProjects/src/app-weixin/vendor/github.com/astaxie/beego/session/couchbase/sess_couchbase.go:40:12: could not import github.com/couchbase/go-couchbase (cannot find package "github.com/couchbase/go-couchbase" in any of:
	/Users/tony/Test/GoToolsProjects/src/app-weixin/vendor/github.com/couchbase/go-couchbase (vendor tree)
	/Users/tony/.bin/go17/src/github.com/couchbase/go-couchbase (from $GOROOT)
	/Users/tony/Test/GoToolsProjects/src/github.com/couchbase/go-couchbase (from $GOPATH))
```

**Comment by shurcooL** [comment]
The generally suggested (by Go authors) unix-y solution to this is to use `grep -v /vendor/`:

```
$ interfacer $(go list ./... | grep -v /vendor/)
```

That way each tool doesn't have to re-implement this functionality.

**Comment by mvdan** [comment]
Agreed. Otherwise this should make its way to a library like `go/loader`.

**Comment by baisibei** [comment]
@mvdan I accept the suggestion by @shurcooL . Btw,  Add this to README is better.
