### ISSUE TITLE
Could we ignore the vendor folder?

### ISSUE THREAD

**Issue by dmowcomber** [mvdan/interfacer#29]
I noticed that the vendor folder is included in the results from interfacer. The vendor folder is a little beyond my control and I don't think that interfacer should check the vendor folder.

For example, one of my projects vendors github.com/stretchr/testify and I see this error from interfacer:
```bash
interfacer ./...
vendor/github.com/stretchr/testify/mock/mock.go:276:36: t can be assert.TestingT
```

**Comment by shurcooL** [comment]
Duplicate of #27.

**Comment by shurcooL** [comment]
Perhaps it's a good idea to update the README to provide a better example of doing:

```
$ interfacer $(go list ./... | grep -v /vendor/)
foo.go:10:19: f can be io.Reader
```

Than the current `interfacer ./...`. Doing that is a really bad idea unless there are no vendor folders, so why does the README recommend it?

**Comment by dmowcomber** [comment]
Thanks for the command to exclude vendor. But maybe vendor should be ignored by default. I and many others have go projects with either a Godeps/_workspace or a vendor/ folder which are filled with mostly 3rd party go projects.

**Comment by shurcooL** [comment]
> But maybe vendor should be ignored by default.

The traditional current solution is for tools to rely on an external tool like `grep -v` for this. That is forced by the fact that it's what the `go` tool does, and it's not a good idea to have each tool deal with this differently.

I don't like this, but that's what it is. If you want to change it, I suggest you file a bug in the Go project and make a convincing rationale for why the `go` tool should change the `./...` pattern to exclude /vendor/ folders when listing import paths it finds (unlikely to happen).

Until then, it would be way worse for tools to deviate in how they treat import path patterns compared to the `go` tool.

References:

- https://golang.org/cmd/go/#hdr-Description_of_package_lists
- https://godoc.org/github.com/kisielk/gotool#ImportPaths

**Comment by dmowcomber** [comment]
I see. I completely agree with you. All go tools should consistently interpret `./...`

Thanks!
