### ISSUE TITLE
[readme.md] so, what exactly is `go/loader`?

### ISSUE THREAD

**Issue by metaleap** [mvdan/interfacer#33]
In the repo readme:

> This package relies on `go/types` for the heavy lifting: name resolution, constant folding and type inference. It also uses `go/loader` to resolve the packages specified by import paths.

I'd be curious to use the latter in other code, but I don't find any actual `go/loader` imports in your `.go` sources here and no mention of `loader` at https://golang.org/pkg/go/ either --- what is it?

**Comment by metaleap** [comment]
Ah OK, found at https://godoc.org/golang.org/x/tools/go/loader

**Comment by shurcooL** [comment]
It might be more clear to refer to it as `x/tools/go/loader` then.

**Comment by mvdan** [comment]
I'll just clean that up - nowadays, the use of `go/types` and `x/tools/go/loader` is common and doesn't need to be in the README.

Also, re-reading that bit made me realise how I introduced #34 :)
