### ISSUE TITLE
Not getting output for your `readme.md`s example

### ISSUE THREAD

**Issue by metaleap** [mvdan/interfacer#34]
Copied the example in `readme.md` nearly verbatim into [here](https://github.com/metaleap/go-devgo/commit/476b05b5590e8e4ed8f02faa9e81eebd55d82687#diff-7d1c2a3334601b6c1958aae0a594cba8R14) (senseless code but just attempting to evade any potential compiler-side code removal..) but `interfacer github.com/metaleap/go-devgo` works for some 1-3 secs but prints nothing, same with `interfacer -v github.com/metaleap/go-devgo` --- what am I missing?

**Comment by mvdan** [comment]
You're right - not sure why that happens. Removing the `processBytes` call seems to fix it. Will investigate.

**Comment by metaleap** [comment]
Not at my end, what's your exact func def here?

**Comment by mvdan** [comment]
@metaleap please try now, it should work. I broke it last week by mistake.

**Comment by metaleap** [comment]
Your fix did the trick, I'm now seeing the expected output. Might wanna incl a simple test -- I try to skimp on them but for linters they're a useful idea 😁

**Comment by metaleap** [comment]
For your amusement, interfacer & unparam in action 😏 

![zentient-01](https://cloud.githubusercontent.com/assets/22109/24732445/4ded47a4-1a71-11e7-8b9d-34098e8941bd.png)

**Comment by mvdan** [comment]
Nice :) If you'd like them to run faster, take a look at metalint: https://github.com/mvdan/lint

**Comment by metaleap** [comment]
From the project description that thing sounds like a good idea! Will keep an eye on it, for now I gotta keep what works already and move on as linting is a very low-priority portion of my evolving vscode-backend-written-in-go  =)  they all run in parallel this way (not node's pretend parallelism) and are categorized into "fast" and "slower" linters where results are polled delayed-ly
