### ISSUE TITLE
inconsistent definition for type ssa.NamedConst during import

### ISSUE THREAD

**Issue by wgliang** [mvdan/interfacer#35]
When I run : go get -u github.com/mvdan/interfacer/cmd/interfacer
I get:

../../mvdan/interfacer/check.go:19: inconsistent definition for type ssa.NamedConst during import
	struct { ssa.object *types.Const; Value *ssa.Const; ssa.pkg *ssa.Package } (in "golang.org/x/tools/go/ssa")
	struct { ssa.object *types.Const; Value *ssa.Const; ssa.pos token.Pos; ssa.pkg *ssa.Package } (in "github.com/mvdan/lint")

../../mvdan/interfacer/check.go:19: method redeclared: ssa.Program.CreateTestMainPackage
	method(*ssa.Program) func(*ssa.Package) *ssa.Package
	method(*ssa.Program) func(...*ssa.Package) *ssa.Package

**Comment by mvdan** [comment]
I can't reproduce this on neither tip nor 1.8.3. What Go version is this?

Have you tried the `go get -u` on an empty `GOPATH`?

**Comment by wgliang** [comment]
I think it's my system environment problem. 
Thks.
